# Generated by Django 5.0.3 on 2024-04-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('preset_name', models.CharField(max_length=100)),
                ('room_name', models.CharField(max_length=100)),
                ('benches', models.IntegerField()),
                ('seats_per_bench', models.IntegerField()),
            ],
        ),
    ]
