# Generated by Django 5.0.3 on 2024-04-13 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_roomdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('preset_name', models.CharField(max_length=100)),
                ('room_name', models.CharField(max_length=100)),
                ('benches', models.IntegerField()),
                ('seats_per_bench', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('benches', models.IntegerField()),
                ('seats_per_bench', models.IntegerField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.preset')),
            ],
        ),
    ]
