# Generated by Django 5.0.3 on 2024-05-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_student_reg_no_student_unique_user_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('bench', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
