# Generated by Django 5.0.3 on 2024-05-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_allocation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_user_reg_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
