# Generated by Django 5.0.3 on 2024-05-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_student_unique_user_reg_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
