# Generated by Django 5.0.3 on 2024-07-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_roomdetails_unique_user_preset'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomdetails',
            name='unique_user_preset',
        ),
    ]
